[profile.release]
panic = "unwind"

[workspace]
members = [
  "nodes/*",
  "pallets/*",
  "runtimes/*",
]

[patch.'https://github.com/paritytech/substrate?branch=rococo-v1']
frame-metadata = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
frame-support = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
frame-support-procedural = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
frame-support-procedural-tools = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
frame-support-procedural-tools-derive = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-application-crypto = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-arithmetic = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-core = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-debug-derive = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-externalities = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-inherents = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-io = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-keystore = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-panic-handler = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-runtime = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-runtime-interface = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-runtime-interface-proc-macro = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-staking = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-state-machine = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-std = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-storage = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-tracing = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-trie = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
sp-wasm-interface = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"}
